wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 256
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier
