wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: random
