_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
