wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 0.5
weight_init:
  value: random
