_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 16
beta:
    value: 0.9
beta1:
    value: 0.9
beta2:
    value: 0.999
dataset:
    value: fashion_mnist
epochs:
    value: 10
epsilon:
    value: 1e-08
hidden_size:
    value: 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
momentum:
    value: 0.9
num_layers:
    value: 4
optimizer:
    value: adam
weight_decay:
    value: 0.0005
weight_init:
    value: Xavier
