wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 25
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 5
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: Xavier
